// This file was autogenerated by ./closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/main.js', ['sf.main'], ['sf.routes.any', 'sf.routes.article', 'sf.routes.conference', 'sf.routes.conferences', 'sf.routes.organization', 'sf.routes.organizations', 'sf.routes.profile', 'sf.routes.result', 'sf.routes.scholar', 'sf.routes.subject', 'sf.routes.topic', 'sf.routes.topics', 'sf.view.Header'], false);
goog.addDependency('../../../src/me.js', ['sf.me'], ['goog.dom.dataset'], false);
goog.addDependency('../../../src/routes/any.js', ['sf.routes.any'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style'], false);
goog.addDependency('../../../src/routes/article.js', ['sf.routes.article'], ['goog.Uri.QueryData', 'goog.dom', 'goog.events', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/routes/conference.js', ['sf.routes.conference'], ['goog.dom', 'goog.events', 'goog.style', 'sf.ui.ConfBox'], false);
goog.addDependency('../../../src/routes/conferences.js', ['sf.routes.conferences'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/routes/organization.js', ['sf.routes.organization'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.dom.dataset', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.structs.Map', 'goog.style', 'sf.ui.Slider'], false);
goog.addDependency('../../../src/routes/organizations.js', ['sf.routes.organizations'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/routes/profile.js', ['sf.routes.profile'], ['goog.dom', 'goog.events', 'goog.net.XhrIo', 'goog.style', 'sf.ui.EditableItem', 'sf.ui.Form', 'sf.ui.ImagePicker'], false);
goog.addDependency('../../../src/routes/result.js', ['sf.routes.result'], ['goog.Uri.QueryData', 'goog.dom', 'goog.events', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/routes/scholar.js', ['sf.routes.scholar'], ['goog.Uri.QueryData', 'goog.dom', 'goog.events', 'goog.net.XhrIo', 'goog.style', 'sf.me', 'sf.ui.EditableItem', 'sf.ui.Form', 'sf.ui.Modal'], false);
goog.addDependency('../../../src/routes/subject.js', ['sf.routes.subject'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style'], false);
goog.addDependency('../../../src/routes/topic.js', ['sf.routes.topic'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.dom.dataset', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/routes/topics.js', ['sf.routes.topics'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer'], false);
goog.addDependency('../../../src/templates/all.js', ['sf.t'], ['soy', 'soydata'], false);
goog.addDependency('../../../src/ui/ConfBox.js', ['sf.ui.ConfBox'], ['goog.Uri.QueryData', 'goog.dom', 'goog.dom.classlist', 'goog.dom.dataset', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style', 'sf.t'], false);
goog.addDependency('../../../src/ui/Dropdown.js', ['sf.ui.Dropdown'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style'], false);
goog.addDependency('../../../src/ui/EditableItem.js', ['sf.ui.EditableItem'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style', 'sf.ui.Form'], false);
goog.addDependency('../../../src/ui/Form.js', ['sf.ui.Form'], ['goog.dom', 'goog.events', 'goog.fx.Transition', 'goog.fx.dom.Slide', 'goog.fx.easing', 'goog.net.EventType', 'goog.net.XhrIo', 'goog.style'], false);
goog.addDependency('../../../src/ui/ImagePicker.js', ['sf.ui.ImagePicker'], ['goog.dom', 'goog.events', 'goog.events.FileDropHandler', 'goog.fx.Transition', 'goog.fx.dom.Slide', 'goog.fx.easing', 'goog.style', 'goog.ui.Slider', 'sf.t'], false);
goog.addDependency('../../../src/ui/Model.js', ['sf.ui.Modal'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style'], false);
goog.addDependency('../../../src/ui/Slider.js', ['sf.ui.Slider'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.style'], false);
goog.addDependency('../../../src/view/Header.js', ['sf.view.Header'], ['goog.dom', 'goog.events', 'goog.style', 'sf.ui.Dropdown'], false);